<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
<context>
    <name>MainWindow</name>
    <message>
        <location filename="../gui/main_window.py" line="39"/>
        <source>Service Launcher App</source>
        <translation>Приложение запуска служб</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="80"/>
        <source>Paste</source>
        <translation>Вставить</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="95"/>
        <location filename="../gui/main_window.py" line="624"/>
        <source>Waiting for input...</source>
        <translation>Ожидание ввода...</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="101"/>
        <location filename="../gui/main_window.py" line="360"/>
        <source>Check</source>
        <translation>Проверить</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="105"/>
        <source>Launch</source>
        <translation>Запустить</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="158"/>
        <source>Restart required</source>
        <translation>Требуется перезагрузка</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="159"/>
        <source>The application must be restarted to switch the language. Restart now?</source>
        <translation>Для смены языка приложение необходимо перезапустить. Перезапустить сейчас?</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="179"/>
        <source>Error</source>
        <translation>Ошибка</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="179"/>
        <source>Failed to save language settings.</source>
        <translation>Не удалось сохранить настройки языка.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="238"/>
        <source>Operation aborted.</source>
        <translation>Операция прервана.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="239"/>
        <source>The operation was aborted by the user.</source>
        <translation>Операция была прервана пользователем.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="243"/>
        <source>Distribution for server edition &apos;{app_type}&apos; and version &apos;{version}&apos; could not be found for installation.</source>
        <translation>Дистрибутив для серверной редакции &apos;{app_type}&apos; и версии &apos;{version}&apos; не найден для установки.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="244"/>
        <location filename="../gui/main_window.py" line="248"/>
        <location filename="../gui/main_window.py" line="251"/>
        <source>An error has occurred:</source>
        <translation>Произошла ошибка:</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="245"/>
        <source>Error: Distribution not found.</source>
        <translation>Ошибка: Дистрибутив не найден.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="250"/>
        <source>Error during operation: details below.</source>
        <translation>Ошибка во время операции: подробности ниже.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="294"/>
        <source>Internal error: unknown dialog type &apos;{dialog_type}&apos;.</source>
        <translation>Внутренняя ошибка: неизвестный тип диалога &apos;{dialog_type}&apos;.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="319"/>
        <source>Unexpected result from app type dialog: &apos;{selected_option}&apos;.</source>
        <translation>Неожиданный результат диалога выбора типа приложения: &apos;{selected_option}&apos;.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="328"/>
        <source>Continuing launch (type selected: {app_type})</source>
        <translation>Продолжение запуска (выбранный тип: {app_type})</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="339"/>
        <source>Continuing launch at user&apos;s request.</source>
        <translation>Продолжение запуска по запросу пользователя.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="369"/>
        <source>Abort</source>
        <translation>Прервать</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="417"/>
        <source>Enter a URL or an LM/AnyDesk ID.</source>
        <translation>Введите URL или LM/AnyDesk ID.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="438"/>
        <location filename="../gui/main_window.py" line="594"/>
        <source>An operation is already in progress. Please wait.</source>
        <translation>Операция уже выполняется. Пожалуйста, подождите.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="441"/>
        <source>Parsing the entered address...</source>
        <translation>Разбор введенного адреса...</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="446"/>
        <source>Invalid input: Failed to parse the address.</source>
        <translation>Неверный ввод: Не удалось разобрать адрес.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="457"/>
        <source>Invalid input: Parsing error ({error}).</source>
        <translation>Неверный ввод: Ошибка разбора ({error}).</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="465"/>
        <source>AnyDesk ID found: {anydesk_id}. Preparing...</source>
        <translation>Найден AnyDesk ID: {anydesk_id}. Подготовка...</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="472"/>
        <source>Clearing AnyDesk cache...</source>
        <translation>Очистка кеша AnyDesk...</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="477"/>
        <source>AnyDesk cache cleared.</source>
        <translation>Кеш AnyDesk очищен.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="480"/>
        <source>Error removing AnyDesk cache folder &apos;{path}&apos;: {error}</source>
        <translation>Ошибка удаления папки кеша AnyDesk &apos;{path}&apos;: {error}</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="482"/>
        <source>Error clearing AnyDesk cache:</source>
        <translation>Ошибка очистки кеша AnyDesk:</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="484"/>
        <source>AnyDesk cache not found, no cleanup required.</source>
        <translation>Кеш AnyDesk не найден, очистка не требуется.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="487"/>
        <source>AnyDesk cache cleanup skipped.</source>
        <translation>Очистка кеша AnyDesk пропущена.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="490"/>
        <source>AnyDesk ID: {anydesk_id}. Requesting password...</source>
        <translation>AnyDesk ID: {anydesk_id}. Запрос пароля...</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="496"/>
        <source>AnyDesk: Enter Password</source>
        <translation>AnyDesk: Введите пароль</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="497"/>
        <source>Enter the password to connect to ID {anydesk_id}:</source>
        <translation>Введите пароль для подключения к ID {anydesk_id}:</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="504"/>
        <source>Launching AnyDesk for {anydesk_id}...</source>
        <translation>Запуск AnyDesk для {anydesk_id}...</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="508"/>
        <source>Error: Path to AnyDesk.exe is not specified in config.ini or the file was not found: &apos;{path}&apos;</source>
        <translation>Ошибка: Путь к AnyDesk.exe не указан в config.ini или файл не найден: &apos;{path}&apos;</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="510"/>
        <location filename="../gui/main_window.py" line="521"/>
        <source>Error launching AnyDesk:</source>
        <translation>Ошибка запуска AnyDesk:</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="515"/>
        <source>AnyDesk launched for {anydesk_id} (PID: {pid}).</source>
        <translation>AnyDesk запущен для {anydesk_id} (PID: {pid}).</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="516"/>
        <source>AnyDesk successfully launched for ID {anydesk_id}.
Process PID: {pid}</source>
        <translation>AnyDesk успешно запущен для ID {anydesk_id}.
PID процесса: {pid}</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="519"/>
        <source>Error launching AnyDesk: {error}</source>
        <translation>Ошибка запуска AnyDesk: {error}</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="524"/>
        <source>AnyDesk launch canceled: no password entered.</source>
        <translation>Запуск AnyDesk отменен: пароль не введен.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="525"/>
        <source>AnyDesk launch canceled: a password was not provided.</source>
        <translation>Запуск AnyDesk отменен: пароль не был предоставлен.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="528"/>
        <location filename="../gui/main_window.py" line="529"/>
        <source>AnyDesk launch canceled by user.</source>
        <translation>Запуск AnyDesk отменен пользователем.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="534"/>
        <source>LiteManager ID found: {lm_id}. Preparing...</source>
        <translation>Найден LiteManager ID: {lm_id}. Подготовка...</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="536"/>
        <source>LiteManager ID detected: {lm_id}. Please enter the password to connect.</source>
        <translation>Обнаружен LiteManager ID: {lm_id}. Пожалуйста, введите пароль для подключения.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="537"/>
        <source>LiteManager ID: {lm_id}. Requesting password...</source>
        <translation>LiteManager ID: {lm_id}. Запрос пароля...</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="543"/>
        <source>LiteManager: Enter Password</source>
        <translation>LiteManager: Введите пароль</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="544"/>
        <source>Enter the password to connect to ID {lm_id}:</source>
        <translation>Введите пароль для подключения к ID {lm_id}:</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="551"/>
        <source>Launching LiteManager for {lm_id}...</source>
        <translation>Запуск LiteManager для {lm_id}...</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="555"/>
        <source>Error: Path to ROMViewer.exe is not specified in config.ini or the file was not found: &apos;{path}&apos;</source>
        <translation>Ошибка: Путь к ROMViewer.exe не указан в config.ini или файл не найден: &apos;{path}&apos;</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="557"/>
        <location filename="../gui/main_window.py" line="568"/>
        <source>Error launching LiteManager:</source>
        <translation>Ошибка запуска LiteManager:</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="562"/>
        <source>LiteManager launched for {lm_id} (PID: {pid}).</source>
        <translation>LiteManager запущен для {lm_id} (PID: {pid}).</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="563"/>
        <source>LiteManager successfully launched for ID {lm_id}.
Process PID: {pid}</source>
        <translation>LiteManager успешно запущен для ID {lm_id}.
PID процесса: {pid}</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="566"/>
        <source>Error launching LiteManager: {error}</source>
        <translation>Ошибка запуска LiteManager: {error}</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="571"/>
        <source>LiteManager launch canceled: no password entered.</source>
        <translation>Запуск LiteManager отменен: пароль не введен.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="572"/>
        <source>LiteManager launch canceled: a password was not provided.</source>
        <translation>Запуск LiteManager отменен: пароль не был предоставлен.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="575"/>
        <location filename="../gui/main_window.py" line="576"/>
        <source>LiteManager launch canceled by user.</source>
        <translation>Запуск LiteManager отменен пользователем.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="583"/>
        <source>Enter a URL or IP:port to check.</source>
        <translation>Введите URL или IP:порт для проверки.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="589"/>
        <source>Invalid request</source>
        <translation>Неверный запрос</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="598"/>
        <source>Performing server check...</source>
        <translation>Выполнение проверки сервера...</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="606"/>
        <source>Aborting operation...</source>
        <translation>Прерывание операции...</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="626"/>
        <source>Clipboard is empty or contains non-text data.</source>
        <translation>Буфер обмена пуст или содержит нетекстовые данные.</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="631"/>
        <source>Exit</source>
        <translation>Выход</translation>
    </message>
    <message>
        <location filename="../gui/main_window.py" line="632"/>
        <source>An operation is in progress. Abort and exit?</source>
        <translation>Выполняется операция. Прервать и выйти?</translation>
    </message>
</context>
</TS>